GET http://localhost:8888/ebook/list?page=1&size=2000

###

GET http://localhost:8888/ebook/all

###
POST http://localhost:8888/ebook/save
Content-Type: application/json

{
  "name": "via"
}

###
GET http://localhost:8888/ebook/delete?id=4
Accept: application/json

###

