GET http://localhost:8888/ebook/list?page=1&size=2000

###

GET http://localhost:8888/ebook/all

###
POST http://localhost:8888/ebook/save
Content-Type: application/json

{
  "id": "138905985585647616",
  "name": "via",
  "description": "666"
}

###

GET http://localhost:8888/ebook/query?name=Spring&size=200


###
GET http://localhost:8888/doc/all/1
